#!/usr/bin/env node
"use strict";
// Bundles each [v8] / [v8ui] wrapper (code/*.v8.js, code/*.v8ui.js) together with the modules it
// requires (code/lib: the engine, no Max APIs; code/max: Max-only helpers
// such as file reading) into one self-contained file: patchers/<name>.bundle.js, next to
// the patches that load it (Max always searches a patch's own folder).
//
// Why bundle: frozen Max for Live devices and built apps don't reliably find
// files that a script loads with require(). A bundle has no runtime requires,
// so what runs while you develop in Max is exactly what gets frozen.
// Patches always load the bundles; Node tests load code/lib directly.
//
//   node tools/build.js           build once
//   node tools/build.js --watch   rebuild whenever code/ changes
//   node tools/build.js --check   exit 1 if the bundles are out of date (CI)

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CODE = path.join(ROOT, "code");
const LIB = path.join(CODE, "lib");
const MAX = path.join(CODE, "max");
const OUT = path.join(ROOT, "patchers");
const REQUIRE = /\brequire\(\s*(["'])([^"']+)\1\s*\)/g;

const relative = (file) => path.relative(ROOT, file).split(path.sep).join("/");

function requiredNames(source) {
  return [...source.matchAll(REQUIRE)].map((match) => match[2]);
}

// Depth-first, so every module is listed after the modules it depends on.
function collect(name, from, seen, modules) {
  if (seen.has(name)) return;
  const file = [LIB, MAX].map((dir) => path.join(dir, name + ".js")).find((f) => fs.existsSync(f));
  if (!file) {
    throw new Error(`${from}: cannot resolve require("${name}"); expected code/lib/${name}.js or code/max/${name}.js`);
  }
  seen.add(name);
  const source = fs.readFileSync(file, "utf8");
  for (const dep of requiredNames(source)) collect(dep, relative(file), seen, modules);
  modules.push({ name, source });
}

function bundle(wrapperFile) {
  const source = fs.readFileSync(wrapperFile, "utf8");
  const seen = new Set();
  const modules = [];
  for (const dep of requiredNames(source)) collect(dep, relative(wrapperFile), seen, modules);

  const out = [];
  out.push(`// GENERATED by tools/build.js from ${relative(wrapperFile)}.`);
  out.push(`// Do not edit: change the source, then run "npm run build".`);
  out.push(``);
  out.push(`var __emi_require = (function () {`);
  out.push(`  var factories = {};`);
  for (const { name, source: moduleSource } of modules) {
    out.push(``);
    out.push(`  // ---- ${name}.js`);
    out.push(`  factories[${JSON.stringify(name)}] = function (exports, module, require) {`);
    out.push(moduleSource.trimEnd());
    out.push(`  };`);
  }
  out.push(``);
  out.push(`  var cache = {};`);
  out.push(`  function load(name) {`);
  out.push(`    if (!Object.prototype.hasOwnProperty.call(cache, name)) {`);
  out.push(`      if (!factories[name]) throw new Error("module not bundled: " + name);`);
  out.push(`      var module = { exports: {} };`);
  out.push(`      cache[name] = module;`);
  out.push(`      factories[name].call(module.exports, module.exports, module, load);`);
  out.push(`    }`);
  out.push(`    return cache[name].exports;`);
  out.push(`  }`);
  out.push(`  return load;`);
  out.push(`})();`);
  out.push(`__emi_require.local = 1;`);
  out.push(``);
  out.push(`// ---- ${relative(wrapperFile)}`);
  out.push(source.replace(REQUIRE, (_match, _quote, name) => `__emi_require(${JSON.stringify(name)})`).trimEnd());
  out.push(``);
  return out.join("\n");
}

// Returns { "patchers/<name>.bundle.js": contents } for every wrapper.
function buildAll() {
  const outputs = {};
  const wrappers = fs
    .readdirSync(CODE)
    .filter((file) => /\.v8(ui)?\.js$/.test(file))
    .sort();
  for (const file of wrappers) {
    const name = file.replace(/\.v8(ui)?\.js$/, ".bundle.js");
    outputs[relative(path.join(OUT, name))] = bundle(path.join(CODE, file));
  }
  return outputs;
}

function existingBundles() {
  if (!fs.existsSync(OUT)) return [];
  return fs
    .readdirSync(OUT)
    .filter((file) => file.endsWith(".bundle.js"))
    .map((file) => relative(path.join(OUT, file)));
}

// Lists bundles that are missing, different from the sources, or stale.
function check() {
  const outputs = buildAll();
  const problems = [];
  for (const [file, contents] of Object.entries(outputs)) {
    const full = path.join(ROOT, file);
    if (!fs.existsSync(full)) problems.push(`${file} is missing`);
    else if (fs.readFileSync(full, "utf8") !== contents) problems.push(`${file} is out of date`);
  }
  for (const file of existingBundles()) {
    if (!(file in outputs)) problems.push(`${file} has no source wrapper in code/`);
  }
  return problems;
}

function write() {
  const outputs = buildAll();
  fs.mkdirSync(OUT, { recursive: true });
  for (const [file, contents] of Object.entries(outputs)) {
    const full = path.join(ROOT, file);
    if (!fs.existsSync(full) || fs.readFileSync(full, "utf8") !== contents) {
      fs.writeFileSync(full, contents);
      console.log(`built ${file}`);
    }
  }
  for (const file of existingBundles()) {
    if (!(file in outputs)) {
      fs.unlinkSync(path.join(ROOT, file));
      console.log(`removed ${file}`);
    }
  }
}

function main(args) {
  if (args.includes("--check")) {
    const problems = check();
    if (problems.length) {
      for (const problem of problems) console.error(problem);
      console.error('Run "npm run build" and commit the result.');
      process.exit(1);
    }
    console.log("bundles are up to date");
    return;
  }
  write();
  if (args.includes("--watch")) {
    let timer = null;
    console.log("watching code/ ...");
    fs.watch(CODE, { recursive: true }, () => {
      clearTimeout(timer);
      timer = setTimeout(() => {
        try {
          write();
        } catch (e) {
          console.error(e.message);
        }
      }, 100);
    });
  }
}

if (require.main === module) {
  try {
    main(process.argv.slice(2));
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}

module.exports = { buildAll, check };
